#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Insurance_Reminder.Resource", IsApplication=true)]

namespace Insurance_Reminder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int list_dialog_items = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int close = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gradient_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient_bg_hover = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sunny = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int ad = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int btnAddTask = 2131099657;
			
			// aapt resource value: 0x7f06001e
			public const int btnDeleteTask = 2131099678;
			
			// aapt resource value: 0x7f060011
			public const int btnNew = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int btnUpdate = 2131099677;
			
			// aapt resource value: 0x7f060002
			public const int dateDisplay = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int freqdisplay = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int imgArrow = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int lblCompanyName = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int lblDueDate = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int lblID = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int lblNoData = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int lblPremiumAmount = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int lblReadonlyCompanyName = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int lblReadonlyDueDate = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int lblReadonlyPremiumAmount = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int list_image = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int lstViewMain = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int pickDate = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int pickTime = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int pickfreq = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayoutButtons = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int tableLayoutReadonly = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int tableRowDueDate = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int tableRowPremiumAmount = 2131099671;
			
			// aapt resource value: 0x7f06000a
			public const int thumbnail = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int timeDisplay = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int txtCompanyName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int txtPremiumAmount = 2131099649;
			
			// aapt resource value: 0x7f06001c
			public const int txtReadonlyDueDate = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int txtReadonlyPremiumAmount = 2131099673;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNewReminder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ReminderDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int UpdateReminderDetails = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int Button_Add_Text = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int Button_Delete_Text = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int Button_New_Text = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int Button_ShowAll_Text = 2131034119;
			
			// aapt resource value: 0x7f050013
			public const int Button_Update_Text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int Close = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int Delete = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int DialogNoButton = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int DialogYesButton = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int Enter_Company_Name = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Enter_Premium_Amount = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int Options = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int Select_Date = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Select_Time = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int ShowDeleteConfirmationMessage = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int UpdateDetails = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int date = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int lblNoData_Text = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int strCompanyName = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int strDueDate = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int strID = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int strPremiumAmount = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int time = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
